"""
WaaaghGate — HTML report generator.

Produces a self-contained HTML security report with findings
grouped by severity, module, and CWE.
"""

from __future__ import annotations

import html
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from krumpa.core import Finding, Severity


_SEVERITY_COLORS = {
    Severity.CRITICAL: "#dc3545",
    Severity.HIGH: "#fd7e14",
    Severity.MEDIUM: "#ffc107",
    Severity.LOW: "#17a2b8",
    Severity.INFO: "#6c757d",
}

_SEVERITY_ORDER = {
    Severity.CRITICAL: 0,
    Severity.HIGH: 1,
    Severity.MEDIUM: 2,
    Severity.LOW: 3,
    Severity.INFO: 4,
}


class HtmlReportGenerator:
    """Generate a self-contained HTML security report."""

    def __init__(
        self,
        *,
        title: str = "GateKrumpa Security Report",
        project_name: str = "",
    ) -> None:
        self._title = title
        self._project = project_name

    def generate(
        self,
        findings: List[Finding],
        *,
        scan_duration: Optional[float] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> str:
        """Produce self-contained HTML string."""
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        _meta = metadata or {}
        sorted_findings = sorted(
            findings,
            key=lambda f: _SEVERITY_ORDER.get(f.severity, 99),
        )

        summary = self._build_summary(findings)
        rows = self._build_rows(sorted_findings)

        duration_str = ""
        if scan_duration is not None:
            duration_str = f"<p><strong>Duration:</strong> {scan_duration:.1f}s</p>"

        project_str = ""
        if self._project:
            project_str = f"<p><strong>Project:</strong> {_esc(self._project)}</p>"

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{_esc(self._title)}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         line-height: 1.6; color: #212529; background: #f8f9fa; padding: 2rem; }}
  .container {{ max-width: 1200px; margin: 0 auto; }}
  h1 {{ margin-bottom: 0.5rem; }}
  .meta {{ color: #6c757d; margin-bottom: 1.5rem; }}
  .summary {{ display: flex; gap: 1rem; margin-bottom: 2rem; flex-wrap: wrap; }}
  .summary-card {{ background: white; border-radius: 8px; padding: 1rem 1.5rem;
                   box-shadow: 0 1px 3px rgba(0,0,0,0.12); min-width: 120px; text-align: center; }}
  .summary-card .count {{ font-size: 2rem; font-weight: bold; }}
  .summary-card .label {{ font-size: 0.85rem; color: #6c757d; text-transform: uppercase; }}
  table {{ width: 100%; border-collapse: collapse; background: white;
           border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.12); }}
  th {{ background: #343a40; color: white; text-align: left; padding: 0.75rem 1rem; }}
  td {{ padding: 0.75rem 1rem; border-bottom: 1px solid #dee2e6; vertical-align: top; }}
  tr:hover {{ background: #f1f3f5; }}
  .badge {{ display: inline-block; padding: 0.2rem 0.6rem; border-radius: 4px;
            color: white; font-size: 0.8rem; font-weight: 600; }}
  .evidence {{ font-family: monospace; font-size: 0.85rem; color: #495057;
               max-width: 400px; word-break: break-all; }}
  .footer {{ margin-top: 2rem; text-align: center; color: #adb5bd; font-size: 0.85rem; }}
</style>
</head>
<body>
<div class="container">
  <h1>{_esc(self._title)}</h1>
  <div class="meta">
    <p><strong>Generated:</strong> {now}</p>
    {project_str}
    {duration_str}
    <p><strong>Total findings:</strong> {len(findings)}</p>
  </div>

  <div class="summary">
    {summary}
  </div>

  <table>
    <thead>
      <tr>
        <th>#</th><th>Severity</th><th>Title</th><th>CWE</th>
        <th>Target</th><th>Evidence</th><th>Remediation</th>
      </tr>
    </thead>
    <tbody>
      {rows}
    </tbody>
  </table>

  <div class="footer">
    Generated by GateKrumpa &mdash; {now}
  </div>
</div>
</body>
</html>"""

    def _build_summary(self, findings: List[Finding]) -> str:
        counts: Dict[str, int] = {}
        for f in findings:
            label = f.severity.value if hasattr(f.severity, 'value') else str(f.severity)
            counts[label] = counts.get(label, 0) + 1

        cards = []
        for sev in [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO]:
            label = sev.value if hasattr(sev, 'value') else str(sev)
            count = counts.get(label, 0)
            color = _SEVERITY_COLORS.get(sev, "#6c757d")
            cards.append(
                f'<div class="summary-card">'
                f'<div class="count" style="color:{color}">{count}</div>'
                f'<div class="label">{_esc(label)}</div></div>'
            )
        return "\n    ".join(cards)

    def _build_rows(self, findings: List[Finding]) -> str:
        rows = []
        for i, f in enumerate(findings, 1):
            color = _SEVERITY_COLORS.get(f.severity, "#6c757d")
            sev_label = f.severity.value if hasattr(f.severity, 'value') else str(f.severity)
            target_str = ""
            if f.target:
                target_str = f"{f.target.method} {f.target.url}" if hasattr(f.target, 'method') else str(f.target)
            cwe_str = f"CWE-{f.cwe}" if f.cwe else ""
            rows.append(
                f"<tr>"
                f"<td>{i}</td>"
                f'<td><span class="badge" style="background:{color}">{_esc(sev_label)}</span></td>'
                f"<td>{_esc(f.title)}</td>"
                f"<td>{_esc(cwe_str)}</td>"
                f"<td>{_esc(target_str)}</td>"
                f'<td class="evidence">{_esc(f.evidence or "")}</td>'
                f"<td>{_esc(f.remediation or '')}</td>"
                f"</tr>"
            )
        return "\n      ".join(rows)


def _esc(text: str) -> str:
    return html.escape(str(text))
