"""
SneakyGits — WAF detection and fingerprinting.

Identifies Web Application Firewalls by:
- Known response headers (X-CDN, Server, X-Powered-By patterns)
- Error page signatures
- Cookie patterns
- Behavioural analysis (known payload blocking patterns)
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Set

from krumpa.core import Finding, Severity, Target

logger = logging.getLogger("krumpa.sneakygits.waf_detector")


@dataclass
class WafSignature:
    """A WAF identification signature."""
    name: str
    vendor: str
    header_patterns: List[str] = field(default_factory=list)
    cookie_patterns: List[str] = field(default_factory=list)
    body_patterns: List[str] = field(default_factory=list)
    status_codes: List[int] = field(default_factory=list)


# Known WAF signatures
WAF_SIGNATURES: List[WafSignature] = [
    WafSignature(name="Cloudflare", vendor="Cloudflare", header_patterns=[r"cf-ray", r"server:\s*cloudflare"], cookie_patterns=[r"__cfduid", r"__cf_bm"]),
    WafSignature(name="AWS WAF", vendor="Amazon", header_patterns=[r"x-amzn-requestid", r"x-amzn-trace-id"], body_patterns=[r"Request blocked"]),
    WafSignature(name="Akamai", vendor="Akamai", header_patterns=[r"x-akamai-", r"akamai"], cookie_patterns=[r"akamai"]),
    WafSignature(name="Imperva/Incapsula", vendor="Imperva", header_patterns=[r"x-cdn:\s*Incapsula", r"x-iinfo"], cookie_patterns=[r"incap_ses", r"visid_incap"]),
    WafSignature(name="F5 BIG-IP ASM", vendor="F5", header_patterns=[r"x-wa-info", r"server:.*bigip"], cookie_patterns=[r"TS[0-9a-f]{6,}", r"BigIP"]),
    WafSignature(name="ModSecurity", vendor="Trustwave", header_patterns=[r"server:.*mod_security", r"x-mod-security"]),
    WafSignature(name="Sucuri", vendor="Sucuri", header_patterns=[r"x-sucuri-id", r"server:\s*Sucuri"], body_patterns=[r"sucuri"]),
    WafSignature(name="Barracuda", vendor="Barracuda", header_patterns=[r"server:.*barracuda"], cookie_patterns=[r"barra_counter_session"]),
    WafSignature(name="Azure Front Door", vendor="Microsoft", header_patterns=[r"x-azure-ref", r"x-fd-healthprobe"]),
    WafSignature(name="Google Cloud Armor", vendor="Google", header_patterns=[r"x-goog-", r"via:.*google"]),
    WafSignature(name="Fastly", vendor="Fastly", header_patterns=[r"x-fastly-request-id", r"via:.*varnish"]),
    WafSignature(name="DDoS-Guard", vendor="DDoS-Guard", header_patterns=[r"server:\s*ddos-guard"]),
    WafSignature(name="Wordfence", vendor="Defiant", body_patterns=[r"Generated by Wordfence", r"wfwaf-"], cookie_patterns=[r"wfwaf-"]),
]

# Known probe payloads that WAFs commonly block
_WAF_PROBE_PAYLOADS = [
    "<script>alert(1)</script>",
    "' OR 1=1--",
    "../../../etc/passwd",
    "${7*7}",
]


class WafDetector:
    """Detect and fingerprint Web Application Firewalls."""

    def __init__(self, http_client: Any = None) -> None:
        self._client = http_client
        self._owns_client = False

    async def detect(self, target: Target) -> List[Finding]:
        """Detect WAF presence on a target."""
        if not self._client:
            return self.analyze_headers(dict(target.headers), target)

        findings: List[Finding] = []
        detected_wafs: List[str] = []

        # Step 1: Normal request to capture headers
        try:
            resp = await self._client.request(method="GET", url=target.url)
            headers_str = "\n".join(f"{k}: {v}" for k, v in resp.headers.items()) if hasattr(resp, 'headers') else ""
            cookies_str = str(resp.headers.get("set-cookie", "")) if hasattr(resp, 'headers') else ""
            body = resp.text[:2000] if hasattr(resp, 'text') else ""

            for sig in WAF_SIGNATURES:
                if self._matches_signature(sig, headers_str, cookies_str, body, resp.status_code):
                    detected_wafs.append(sig.name)
        except Exception as exc:
            logger.debug("WAF detection error: %s", exc)

        # Step 2: Send probe payloads to detect blocking behaviour
        blocked_count = 0
        for payload in _WAF_PROBE_PAYLOADS:
            try:
                probe_url = f"{target.url}?test={payload}"
                resp = await self._client.request(method="GET", url=probe_url)
                if resp.status_code in (403, 406, 429, 501, 503):
                    blocked_count += 1
            except Exception:
                pass

        if blocked_count >= 2:
            if not detected_wafs:
                detected_wafs.append("Unknown WAF")

        if detected_wafs:
            findings.append(Finding(
                title=f"WAF detected: {', '.join(detected_wafs)}",
                description=(
                    f"Web Application Firewall(s) detected at {target.url}: "
                    f"{', '.join(detected_wafs)}. "
                    f"{blocked_count}/{len(_WAF_PROBE_PAYLOADS)} probe payloads were blocked."
                ),
                severity=Severity.INFO,
                target=target,
                evidence=f"WAFs: {detected_wafs}, blocked: {blocked_count}/{len(_WAF_PROBE_PAYLOADS)}",
                remediation="Note: WAF presence is informational. Ensure WAF rules are properly configured.",
                tags=["waf", "recon", "fingerprint"],
            ))

        return findings

    def analyze_headers(
        self, headers: Dict[str, str], target: Optional[Target] = None,
    ) -> List[Finding]:
        """Offline WAF detection from headers only."""
        findings: List[Finding] = []
        headers_str = "\n".join(f"{k}: {v}" for k, v in headers.items())
        cookies_str = headers.get("set-cookie", headers.get("Set-Cookie", ""))
        detected: List[str] = []

        for sig in WAF_SIGNATURES:
            if self._matches_signature(sig, headers_str, cookies_str, "", 0):
                detected.append(sig.name)

        if detected:
            t = target or Target(url="unknown")
            findings.append(Finding(
                title=f"WAF detected (headers): {', '.join(detected)}",
                description=f"WAF signatures found in response headers: {', '.join(detected)}",
                severity=Severity.INFO,
                target=t,
                evidence=f"Detected: {detected}",
                tags=["waf", "recon"],
            ))

        return findings

    @staticmethod
    def _matches_signature(
        sig: WafSignature,
        headers_str: str,
        cookies_str: str,
        body: str,
        status_code: int,
    ) -> bool:
        """Check if response matches a WAF signature."""
        for pattern in sig.header_patterns:
            if re.search(pattern, headers_str, re.IGNORECASE):
                return True
        for pattern in sig.cookie_patterns:
            if re.search(pattern, cookies_str, re.IGNORECASE):
                return True
        for pattern in sig.body_patterns:
            if re.search(pattern, body, re.IGNORECASE):
                return True
        if sig.status_codes and status_code in sig.status_codes:
            return True
        return False
